app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django_filters.views import FilterView
from app import views
from app.models import TblProviderMaster

urlpatterns = [
    # path(r'', views.login, name='login'),
    path(r'', views.home, name='home'),
    path('signin', views.sign_in, name='signin'),
    path('signout', views.sign_out, name='signout'),
    path('callback', views.callback, name='callback'),
    path(r'main/', views.main, name='main'),
    path(r'<pk>/details', views.appealDetailsView, name='appeal-details'),
    path(r'<pk>/details/add-issue', views.addIssueView, name='add-issue'),
    path(r'<pk>/details/add-prov', views.addProviderToGroup, name='add-prov'),
    path(r'edit/details/issue/<pk>', views.providerMasterUpdateView, name='edit-case-issue'),
    path(r'edit/details/due-dates/<pk>', views.updateDueDateProgress, name='update-due-progress'),
    path(r'edit/npr-due-date/<pk>', views.updateNPRDueDateProgress, name='update-npr-progress'),
    path(r'<pk>/details/add-due-dates/', views.addCriticalDueView, name='add-due'),
    path(r'<pk>/transfer-issue/', views.transferIssueView, name='transfer-issue'),
    path(r'<pk>/withdraw-issue/', views.withdrawFromCase, name='withdraw-from-case'),
    path(r'<pk>/ScheduleG/cover-letter/', views.createFormGCoverLetter, name='form-g-cover-letter'),
    path(r'<pk>/ScheduleG/issue-statement/', views.createFormGIssueState, name='form-g-issue-state'),
    path(r'<pk>/ScheduleG/toc/', views.createFormGToc, name='form-g-toc'),
    path(r'<pk>/ScheduleG/exhibits/', views.createFormGExhibits, name='form-g-exhibits'),
    path(r'<pk>/ScheduleG/form-g/', views.createFormG, name='form-g'),
    path(r'new/appeal/', views.NewAppealMasterView.as_view(), name='new-appeal'),
    path(r'parent-master/', views.parentMasterView, name='parent-master'),
    path(r'new/parent/', views.NewSystemView.as_view(), name='new-parent'),
    path(r'edit/parent/<pk>/', views.parentUpdateView, name='update-parent'),
    path(r'new/hosp-contact/<pk>', views.NewHospContactView, name='new-hosp-contact'),
    path(r'provider-master/', views.providerMasterView, name='provider-master'),
    path(r'new/provider/', views.NewProviderView.as_view(), name='new-provider'),
    path(r'edit/prov/<pk>', views.providerNameUpdateView, name='update-provider'),
    path(r'issue-master/', views.issueMasterView, name='issue-master'),
    path(r'issue-master/detail/<pk>', views.issueDetailView, name='issue-detail'),
    path(r'new-issue/', views.NewIssueView.as_view(), name='new-issue'),
    path(r'edit/issue/<pk>/', views.issueEditView, name='edit-issue'),
    path(r'staff-master/', views.staffMasterView, name='staff-master'),
    path(r'new/staff/', views.NewStaffView.as_view(), name='new-staff'),
    path(r'mac-master/', views.fiMasterView, name='mac-master'),
    path(r'mac-master/<pk>/edit', views.editFI, name='edit-mac'),
    path(r'new/mac/', views.NewFIView.as_view(), name='new-mac'),
    path(r'prrb-master/', views.prrbMasterView, name='prrb-master'),
    path(r'new/prrb/', views.NewPRRBContactView.as_view(), name='new-prrb'),
    path(r'prrb-master/<pk>/edit', views.editPRRB, name='edit-prrb'),
    path(r'^search/$', views.searchCriticalDueDates, name='due-master'),
    path(r'search-two', views.searchCriticalDueDatesTwo, name='due-master-two'),
    path(r'provmaster-filter', views.providerAppealDetails, name='prov-appeal-details'),
    path(r'provmaster-filter', FilterView.as_view(model=TblProviderMaster), name='prov-appeal-details'),
    path(r'group-report/', views.groupReport, name='group-report'),
    path(r'provider-report/', views.providerReport, name='provider-report')

]

appeals/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path(r'', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
import datetime
from datetime import timedelta
from django.db import models
import uuid


# Models for Appeal Issues

class TblCategoryMaster(models.Model):
    categoryID = models.AutoField(db_column='categoryID', primary_key=True)
    categoryName = models.CharField(
        db_column='categoryName', max_length=50, blank=True, null=True)
    categoryKey = models.CharField(
        db_column='categoryKey', unique=True, max_length=10, blank=True, null=True)
    categoryDescription = models.CharField(db_column='categoryDescription', max_length=150, blank=True,
                                           null=True)

    class Meta:
        db_table = 'tblCategoryMaster'

    def __str__(self):
        return '%s - %s' % (self.categoryID, self.categoryKey)


class TblTitleMaster(models.Model):
    titleAbbreviation = models.CharField(
        db_column='titleAbbreviation', primary_key=True, max_length=5)
    titleFull = models.CharField(
        db_column='titleFull', max_length=50, blank=True, null=True)

    class Meta:
        db_table = 'tblTitleMaster'

    def __str__(self):
        return self.titleFull


class TblStaffMaster(models.Model):
    staffID = models.AutoField(db_column='staffID', primary_key=True)
    staffLastName = models.CharField(
        db_column='staffLastName', max_length=50, blank=True, null=True)
    staffFirstName = models.CharField(
        db_column='staffFirstName', max_length=50, blank=True, null=True)
    staffEmail = models.EmailField(
        db_column='staffEmail', max_length=100, blank=True, null=True)
    titleAbbreviation = models.ForeignKey('TblTitleMaster', on_delete=models.CASCADE, db_column='titleAbbreviation',
                                          blank=True, null=True)

    class Meta:
        db_table = 'tblStaffMaster'

    def __str__(self):
        return self.staffLastName


class TblIssueMaster(models.Model):
    issueID = models.AutoField(db_column='issueID', primary_key=True)
    issueSRGID = models.IntegerField(null=True, blank=True)
    issueName = models.CharField(
        db_column='issueName', max_length=100, blank=True, null=True)
    issueAbbreviation = models.CharField(
        db_column='issueAbbreviation', max_length=25, blank=True, null=True)
    issueShortDescription = models.TextField(
        db_column='issueShortDescription', blank=True, null=True)
    issueLongDescription = models.TextField(
        db_column='issueLongDescription', blank=True, null=True)
    categoryID = models.ForeignKey('TblCategoryMaster', on_delete=models.CASCADE, db_column='categoryID',
                                   blank=True, null=True)
    staffID = models.ForeignKey('TblStaffMaster', on_delete=models.CASCADE, db_column='staffID',
                                blank=True, null=True)

    class Meta:
        db_table = 'tblIssueMaster'
        ordering = ['issueSRGID']

    def __str__(self):
        return '{0}-{1}'.format(str(self.issueSRGID), self.issueName)


# Models for Provider Name tables


class TblStateMaster(models.Model):
    stateID = models.CharField(
        db_column='stateID', primary_key=True, max_length=2)
    stateName = models.CharField(db_column='stateName', max_length=50)

    class Meta:
        db_table = 'tblStateMaster'
        ordering = ['stateID']

    def __str__(self):
        return self.stateID


class TblHospContactMaster(models.Model):
    hospContactID = models.AutoField(primary_key=True)
    hospContactFirstName = models.CharField(max_length=45, blank=True, null=True)
    hospContactLastName = models.CharField(max_length=45, blank=True, null=True)
    hospContactTitle = models.CharField(max_length=75, blank=True, null=True)
    hospContactEmail = models.EmailField(blank=True, null=True)
    parentID = models.ForeignKey('TblParentMaster', on_delete=models.CASCADE, blank=True, null=True)


class TblParentMaster(models.Model):
    parentID = models.CharField(
        db_column='parentID', primary_key=True, max_length=50)
    parentFullName = models.CharField(
        db_column='parentFullName', max_length=255, blank=True, null=True)
    parentAddress = models.CharField(max_length=100, null=True, blank=True)
    parentCity = models.CharField(max_length=50, null=True, blank=True)
    stateID = models.ForeignKey(
        'TblStateMaster', on_delete=models.CASCADE, blank=True, null=True)
    parentZIP = models.IntegerField()

    class Meta:
        db_table = 'tblParentMaster'

    def __str__(self):
        return self.parentFullName


class TblProviderNameMaster(models.Model):
    providerID = models.CharField(
        db_column='providerID', primary_key=True, max_length=7)
    providerName = models.CharField(
        db_column='providerName', max_length=50, blank=True, null=True)
    providerFYE = models.DateField(
        db_column='providerFYE', blank=True, null=True)
    providerCity = models.CharField(
        db_column='providerCity', max_length=50, blank=True, null=True)
    providerCounty = models.CharField(
        db_column='providerCounty', max_length=50, blank=True, null=True)
    providerIsClient = models.BooleanField(blank=True, null=True)
    stateID = models.ForeignKey(
        'TblStateMaster', on_delete=models.CASCADE, db_column='stateID', blank=True, null=True)
    parentID = models.ForeignKey('TblParentMaster', on_delete=models.CASCADE, db_column='parentID', blank=True,
                                 null=True)
    fiID = models.ForeignKey('TblFIMaster', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'tblProviderNameMaster'

    def __str__(self):
        return self.providerID

    def getParentName(self):
        return self.parentID.parentFullName

    def properProvName(self):
        return self.providerName.title()


class TblProviderContactMaster(models.Model):
    contactID = models.AutoField(db_column='contactID', primary_key=True)
    contactLastName = models.CharField(
        db_column='contactLastName', max_length=50, blank=True, null=True)
    contactFirstName = models.CharField(
        db_column='contactFirstName', max_length=50, blank=True, null=True)
    contactTitle = models.CharField(
        db_column='contactTitle', max_length=50, blank=True, null=True)
    contactEmail = models.EmailField(
        db_column='contactEmail', max_length=50, blank=True, null=True)
    contactPhone = models.IntegerField(
        db_column='contactPhone', blank=True, null=True)
    providerID = models.ForeignKey(
        'TblProviderNameMaster', on_delete=models.CASCADE, db_column='providerID')
    parentID = models.ForeignKey('TblParentMaster', on_delete=models.CASCADE, db_column='parentID', blank=True,
                                 null=True)

    class Meta:
        db_table = 'tblProviderContactMaster'


class TblFIMaster(models.Model):
    fiID = models.AutoField(db_column='fiID', primary_key=True)
    fiLastName = models.CharField(
        db_column='fiLastName', max_length=50, blank=True, null=True)
    fiFirstName = models.CharField(
        db_column='fiFirstName', max_length=50, blank=True, null=True)
    fiName = models.CharField(
        db_column='fiName', max_length=75, blank=True, null=True)
    fiTitle = models.CharField(
        db_column='fiTitle', max_length=50, blank=True, null=True)
    fiJurisdiction = models.CharField(
        db_column='fiJurisdiction', max_length=10, blank=True, null=True)
    fiEmail = models.EmailField(
        db_column='fiEmail', max_length=50, blank=True, null=True)
    fiAppealsEmail = models.EmailField(
        db_column='fiAppealsEmail', max_length=50, blank=True, null=True)
    fiPhone = models.IntegerField(db_column='fiPhone', blank=True, null=True)
    fiStreet = models.CharField(
        db_column='fiStreet', max_length=50, blank=True, null=True)
    fiStreetTwo = models.CharField(
        db_column='fiStreetTwo', max_length=50, blank=True, null=True)
    fiCity = models.CharField(
        db_column='fiCity', max_length=50, blank=True, null=True)
    stateID = models.ForeignKey(
        'TblStateMaster', on_delete=models.CASCADE, db_column='stateID', blank=True, null=True)
    fiZip = models.IntegerField(db_column='fiZip', blank=True, null=True)

    class Meta:
        db_table = 'tblFIMaster'

    def __str__(self):
        return '{0}-{1}'.format(self.fiName, self.fiJurisdiction)

    def get_id(self):
        return self.fiID


class TblPRRBContactMaster(models.Model):
    prrbContactID = models.AutoField(
        db_column='prrbContactID', primary_key=True)
    prrbContactLastName = models.CharField(
        db_column='prrbContactLastName', max_length=50, blank=True, null=True)
    prrbContactFirstName = models.CharField(
        db_column='prrbContactFirstName', max_length=50, blank=True, null=True)
    prrbContactEmailAddress = models.EmailField(db_column='prrrbContactEmailAddress', max_length=50, blank=True,
                                                null=True)
    prrbContactGenEmailAddress = models.EmailField(db_column='prrbContactGenEmailAddress', max_length=100, blank=True,
                                                   null=True)  # Field name made lowercase.
    prrbContactPhone = models.IntegerField(
        db_column='prrbContactPhone', blank=True, null=True)
    prrbContactStreet = models.CharField(
        db_column='prrbContactStreet', max_length=50, blank=True, null=True)
    prrbContactStreetTwo = models.CharField(
        db_column='prrbContactStreetTwo', max_length=50, blank=True, null=True)
    prrbContactCity = models.CharField(
        db_column='prrbContactCity', max_length=50, blank=True, null=True)
    prrbContactZipCode = models.IntegerField(
        db_column='prrbContactZipCode', blank=True, null=True)
    stateID = models.ForeignKey(
        'TblStateMaster', on_delete=models.CASCADE, db_column='stateID', blank=True, null=True)

    class Meta:
        db_table = 'tblPRRBContactMaster'

    def __str__(self):
        return self.prrbContactLastName

app/templates/main/criticalDatesMaster.html
{% extends "main/layout.html" %}

{% block content %}
{% load humanize %}
<div class="container-fluid mt-5">
    <h5 class="font-weight-bold text-uppercase pl-1 pt-1">Critical Due Dates</h5>
    <hr class="mt-0"/>
    <form method="get">
        <div class="container">
            <h5>Filter</h5>
            <div class="row">
                {% for field in filter.form.visible_fields %}
                    <div class="col-sm-4 border my-2">
                        {{ field.label_tag }} <br>
                        {{ field }}
                </div>
                {% endfor %}
            </div>

        <button type="submit" class="mt-2 btn btn-primary w-25">Filter Due Dates</button>
        </div>
    </form>


    <hr class="mt-3"/>

    <table class="table table table-hover table-bordered">
        <thead class="thead-light text-center">
            <tr>
                <th scope="col">Case Number</th>
                <th scope="col">Due Date</th>
                <th scope="col">Action</th>
                <th scope="col">Progress</th>
            </tr>
        </thead>
            {% for criticalDate in filter.qs %}
            <tr>
                <td class="text-center" style="width: 100px">{{ criticalDate.caseNumber }}</td>
                <td class="text-center" style="width: 75px">{{ criticalDate.dueDate|date:'m/d/Y' }}</td>
                <td>{{ criticalDate.get_action_note}}</td>
                {% if criticalDate.progress == 'Not Started' %}
                    <td class="text-center bg-warning" style="width: 175px;"><a class="text-dark" href=""><i class="far fa-circle"></i> {{ criticalDate.progress }}</a></td>
                {% elif criticalDate.progress == 'In Progress' %}
                    <td class="text-center bg-primary text-white" style="width: 175px;"><a class="text-white" href=""><i class="fas fa-spinner"></i> {{ criticalDate.progress }}</a></td>
                {% elif criticalDate.progress == 'Completed' %}
                    <td class="text-center bg-success text-white" style="width: 175px;"><a class="text-white" href=""><i class="far fa-check-circle"></i> {{ criticalDate.progress }}</a></td>
                {% else %}
                    <td class="text-center bg-info" style="width:175px;">{{ criticalDate.progress }}</td>
                {% endif %}
            </tr>
            {% endfor %}
    </table>
</div>


{% endblock %}

app/templates/main/criticalDatesMasterTwo.html
{% extends "main/layout.html" %}

{% block content %}
{% load humanize %}
<div class="container-fluid mt-5">
    <h5 class="font-weight-bold text-uppercase pl-1 pt-1">Critical Due Dates</h5>
    <hr class="mt-0"/>
    <form method="get">
        <div class="container">
            <h5>Filter</h5>
            <div class="row">
                {% for field in filter.form.visible_fields %}
                    <div class="col-sm-4 border my-2">
                        {{ field.label_tag }} <br>
                        {{ field }}
                </div>
                {% endfor %}
            </div>
        <button type="submit" class="mt-2 btn btn-primary w-25">Filter Due Dates</button>
        </div>
    </form>


    <hr class="mt-3"/>

    <table class="table table table-hover table-bordered">
        <thead class="thead-light text-center">
            <tr>
                <th scope="col">Case Number</th>
                <th scope="col">Case Name
                <th scope="col">Action</th>
                <th scope="col">Due Date</th>
                <th scope="col">Progress</th>
            </tr>
        </thead>
            {% for criticalDate in filter.qs %}
                {% for due in criticalDate.criticaldatesmaster_set.all %}
                        <tr>
                            <td class="text-center" style="width: 100px">{{ due.caseNumber }}</td>
                            <td class="">{{ criticalDate.appealName }}</td>
                            <td>{{ due.get_action_note}}</td>
                            <td class="text-center" style="width: 75px">{{ due.dueDate|date:'m/d/Y' }}</td>
                            {% if due.progress == 'Not Started' %}
                                <td class="text-center bg-warning" style="width: 150px;"><a class="text-dark" href=""><i class="far fa-circle"></i> {{ due.progress }}</a></td>
                            {% elif due.progress == 'In Progress' %}
                                <td class="text-center bg-primary text-white" style="width: 150px;"><a class="text-white" href=""><i class="fas fa-spinner"></i> {{ due.progress }}</a></td>
                            {% elif due.progress == 'Completed' %}
                                <td class="text-center bg-success text-white" style="width: 150px;"><a class="text-white" href=""><i class="far fa-check-circle"></i> {{ due.progress }}</a></td>
                            {% else %}
                                <td class="text-center bg-info" style="width: 175px;"><a class="text-dark" href="{% url 'update-due-progress' due.id %}">{{ due.progress }}</a></td>
                            {% endif %}
                        </tr>
                {% endfor %}
            {% endfor %}
    </table>
</div>


{% endblock %}

app/templates/main/fiMaster.html
{% extends "main/layoutV2.html" %}

{% block content %}
{% load humanize %}

<div class="container-fluid">
    <div class="row mb-0 d-flex justify-content-center">
        <div class="col-xxl-10 col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-header srg-bg-primary d-flex justify-content-between">
                    <span class="fs-3 display-6 srg-text-secondary">MAC Master</span>
                    <a class="fs-6 d-flex srg-text-secondary align-items-center gap-1" href="{% url 'new-mac' %}"><svg class="bi"><use xlink:href="#plus-fill"></use></svg>New MAC</a>
                </div>
                <div class="class-body px-4">
                    {% regroup all_fis by fiName as all_macs_list %}
                    {% for fiName in all_macs_list %}
                        <div class="card my-4">
                            <div class="card-header srg-bg-secondary srg-header">
                                <span class="fs-4 display-6">{{ fiName.grouper }}</span>
                            </div>
                            <div class="card-body px-4">
                                <div class="row">
                                    <table class="srg-table" style="font-size:12pt">
                                        <tr>
                                            <th>JD</th>
                                            <th>Name</th>
                                            <th>Title</th>
                                            <th>Email</th>
                                            <th>Address</th>
                                        </tr>
                                        {% for mac in fiName.list %}
                                            <tr>
                                                <td>{{ mac.fiJurisdiction }}</td>
                                                <td>{{ mac.fiFirstName }} {{ mac.fiLastName }}</td>
                                                <td>{{ mac.fiTitle }}</td>
                                                <td>{{ mac.fiEmail }}</td>
                                                <td>
                                                    {{ mac.fiStreet }},
                                                    {{ mac.fiStreetTwo }},
                                                    {{ mac.fiCity }}, {{ mac.stateID }}</td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/main/formG.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->

    {% load static %}

    <link rel="stylesheet" {% static 'site.css' %}>

    <meta charset="UTF-8">

    <title>Schedule G</title>

    <style>
        @page {
            size: letter landscape;
            margin-left: 2cm;

            @frame header_frame {           /* Static Frame */
                -pdf-frame-content: header_content;
            }
            @frame content_frame {          /* Content Frame */
                left: 50pt; width: 512pt; top: 90pt; height: 632pt;
            }
            @frame footer_frame {           /* Another static Frame */
                -pdf-frame-content: footer_content;
            }
        }

        .border {
            border: black 1px solid;
        }

        .text-center {
            text-align:center!important
        }

        .container-fluid {
            width:1000px;
            padding-right:15px;
            padding-left:15px;
            margin-right:auto;
            margin-left:auto
        }

        .row {
            display: flex;
        }

        .col {
            flex:1;
        }

        .col:first-child {
            margin-right: 20px;
        }

        .list-group {
            padding-left:0;
            margin-bottom:0;
        }

        .list-group-item {
            position:relative;
            display:block;
            padding:1px;
            background-color:#fff;
            list-style-type: none;
        }

    </style>
</head>
<body>
    <div class="container-fluid">
        <div id="header_content" class="row" style="width: 1366px;">


            <h6 class="text-center" style="margin-top: 8px;">Model Form G - Schedule of Providers in Group</h6>
            <div class="col">
                <ul class="list-group">
                    <li class="list-group-item" style="padding: 0px;"><span style="padding: 0px;">Case N.:</span></li>
                    <li class="list-group-item" style="padding: 0px;"><span style="padding: 0px;">Group Name:</span></li>
                    <li class="list-group-item" style="padding: 0px;"><span style="padding: 0px;">Group Representative:</span></li>
                    <li class="list-group-item" style="padding: 0px;"><span style="padding: 0px;">Lead Intermediary:</span></li>
                    <li class="list-group-item" style="padding: 0px;"><span>Issue:</span></li>
                </ul>
            </div>
            <div class="col">
                <ul class="list-group">
                    <li class="list-group-item" style="padding: 0;"><span>Page <pdf:pagenumber></pdf:pagenumber> of <pdf:pagecount></pdf:pagecount> </span></li>
                    <li class="list-group-item" style="padding: 0;"><span>Date Prepared:</span></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="table-responsive table-bordered" style="border: 1px solid black">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;">#</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;width: 15rem">Provider Name / Location<br>(city, county, state)</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;">FYE</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;padding-right: 0;padding-left: 0;">A<br>Date of Final <br>Determination</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;padding-right: 0;padding-left: 0;">B<br>Date of<br>Hearing<br>Request /<br>Add Issue<br>Request</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;padding-right: 0;padding-left: 0;">C<br>No. of<br>Days</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;word-wrap: break-word; width: 5px">D<br>Audit<br>Adj. No.</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;padding-right: 0;padding-left: 0;">E<br>Amount in<br>Controversy</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;padding-right: 0;padding-left: 0;">F<br>Prior Case<br>No(s).</th>
                                <th class="text-center" style="font-size: 10px;border: 1px solid black;padding-right: 0;padding-left: 0;">G<br>Date of<br>Direct Add /<br>Transfer(s)<br>to Group</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr style="height: 85px;border: 1px solid black;">
                                <td style="text-align: center;border: 1px solid black;">1</td>
                                <td style="border: 1px solid black">Loretto Hospital / Chicago, Cook, IL</td>
                                <td class="text-center" style="border: 1px solid black;">12/31/2021</td>
                                <td class="text-center" style="border: 1px solid black;padding-right: 0;padding-left: 0;">10/01/2021</td>
                                <td class="text-center" style="border: 1px solid black;padding-right: 0;padding-left: 0;">08/17/2021</td>
                                <td class="text-center" style="border: 1px solid black;padding-right: 0;padding-left: 0;">05/22/2021</td>
                                <td class="text-center" style="border: 1px solid black; word-wrap: break-word; width: 5px">133,154,354,516,564,564,133,154,354,516,564,564</td>
                                <td class="text-center" style="border: 1px solid black;padding-right: 0;padding-left: 0;">$1,000,000</td>
                                <td class="text-center" style="border: 1px solid black;padding-right: 0;padding-left: 0;">19-2222</td>
                                <td class="text-center" style="border: 1px solid black;padding-right: 0;padding-left: 0;">04/22/2021</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/main/parentMaster.html
{% extends "main/layoutV2.html" %}

{% block content %}
{% load humanize %}

<div class="container-fluid">
    <div class="row mb-0">
        <div class="card p-0">
            <div class="card-header srg-bg-primary d-flex justify-content-between">
                <span class="fs-3 display-6 srg-text-secondary">
                    Parent Master
                </span>
                <a class="fs-6 d-flex srg-text-secondary align-items-center gap-1" href="{% url 'new-parent' %}">
                        <svg class="bi"><use xlink:href="#plus-fill"></use></svg>New Parent</a>
            </div>
            <div class="card-body">
                <div class="row d-flex justify-content-between">
                    {% for parent in all_parents %}
                        <div class="col-4 my-2">
                            <div class="card">
                                <div class="card-header srg-bg-secondary srg-header">
                                    <span class="fs-5 display-6">{{ parent.parentFullName }}</span>
                                </div>
                                <div class="card-body">
                                    <p class="srg-header fw-bold mb-0">Address:</p>
                                    <address>
                                        {{ parent.parentAddress }} <br/>
                                        {{ parent.parentCity }}, {{ parent.stateID }} {{ parent.parentZIP }}
                                    </address>
                                    <p class="srg-header fw-bold">Contacts:</p>
                                    <table class="srg-table">
                                        <tr>
                                            <th>Name</th>
                                            <th>Title</th>
                                            <th>Email</th>
                                        </tr>
                                        {% for contact in parent.tblhospcontactmaster_set.all %}
                                            <tr>
                                                <td>{{ contact.hospContactFirstName }} {{ contact.hospContactLastName }}</td>
                                                <td>{{ contact.hospContactTitle }}</td>
                                                <td>{{ contact.hospContactEmail }}</td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                                <div class="card-footer d-flex justify-content-end py-2 bg-transparent gap-2">
                                    <a class="srg-btn-primary" data-toggle="tooltip" data-placement="top" title="Edit Parent" href="{% url 'update-parent' parent.parentID %}">
                                        Edit Parent
                                    </a>
                                    <a class="srg-btn-secondary" data-toggle="tooltip" data-placement="top" title="Edit Parent" href="{% url 'new-hosp-contact' parent.parentID %}">
                                        Add Contact
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}